apiVersion: v1
kind: Pod
metadata:
  name: s3-test-pod-1
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["/bin/sh"]
    args: ["-c", "echo 'Testing S3 CSI driver' > /data/test.txt && tail -f /dev/null"]
    volumeMounts:
    - name: s3-volume
      mountPath: /data
  volumes:
  - name: s3-volume
    persistentVolumeClaim:
      claimName: s3-pvc