apiVersion: v1
kind: Pod
metadata:
  name: s3-test-pod-2
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: s3-volume
      mountPath: /data
  volumes:
  - name: s3-volume
    persistentVolumeClaim:
      claimName: s3-pvc