apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: s3-csi
provisioner: s3.csi.aws.com
parameters:
  bucketName: uat-bk
  region: ap-southeast-1
  type: standard
reclaimPolicy: Retain
volumeBindingMode: Immediate